name       : haskell-base-orphans
version    : '0.7'
release    : 3
source     :
    - https://hackage.haskell.org/package/base-orphans-0.7/base-orphans-0.7.tar.gz : 0aaddc39e3d0bba13acfcf0009ef57bf91d2ee74b295041d63e14c6caf4dee14
license    : MIT
component  : programming.haskell
summary    : base-orphans defines orphan instances that mimic instances available
    in later versions of base to a wider (older) range of compilers.
description: |
    base-orphans defines orphan instances that mimic instances available in later versions of base to a wider (older) range of compilers.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
