name       : haskell-base-orphans
version    : 0.8.2
release    : 4
source     :
    - https://hackage.haskell.org/package/base-orphans-0.8.2/base-orphans-0.8.2.tar.gz : 2a8062385e5d5dee418428a22c72b9391557bc1fe2f93bd643f7754b36b9eb01
license    : MIT
component  : programming.haskell
summary    : base-orphans defines orphan instances that mimic instances available in later versions of base to a wider (older) range of compilers.
description: |
    base-orphans defines orphan instances that mimic instances available in later versions of base to a wider (older) range of compilers.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
