name       : haskell-base-orphans
version    : 0.5.4
release    : 1
source     :
    - http://hackage.haskell.org/package/base-orphans-0.5.4/base-orphans-0.5.4.tar.gz : 04075283606b3633f4b0c72f849a6df1b0519421ad099d07d3e72de589056263
license    : MIT
component  : programming.haskell
summary    : base-orphans defines orphan instances that mimic instances available in later versions of base to a wider (older) range of compilers.
description: |
    base-orphans defines orphan instances that mimic instances available in later versions of base to a wider (older) range of compilers.
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
